# Numpy
**when we have to deal with number,matrix,linear algebra etc.

In [ ]:
#matrix(2d or 1d)
#create an array

In [1]:
import numpy as np

In [2]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_lists=([1,2,3],[4,5,6],[7,8,9])
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(5,28)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27])

In [6]:
np.arange(5,35,6)

array([ 5, 11, 17, 23, 29])

In [7]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [11]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [13]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [15]:
np.random.rand(2,4)

array([[0.13216179, 0.46571812, 0.54790481, 0.43457332],
       [0.82419623, 0.17252902, 0.77938805, 0.1345717 ]])

In [16]:
np.random.randn(2,4)

array([[-0.78710034, -1.57986372, -0.8782665 , -0.21865958],
       [ 0.09051175,  0.30300019,  1.05424479, -2.04196922]])

In [17]:
np.random.rand(2,5)

array([[0.15921559, 0.57376018, 0.52723965, 0.69721981, 0.92245959],
       [0.22446451, 0.55833866, 0.73639991, 0.75451008, 0.55392374]])

In [18]:
np.random.randint(0,10,5)

array([4, 9, 0, 1, 4])

In [19]:
np.random.randint(10,100,15)

array([90, 93, 56, 30, 57, 95, 20, 91, 15, 77, 38, 42, 43, 35, 49])

In [20]:
np.random.randint(20,56,100)

array([21, 49, 48, 44, 41, 24, 36, 36, 52, 39, 42, 34, 20, 31, 25, 50, 24,
       30, 31, 48, 38, 20, 51, 20, 41, 55, 38, 24, 54, 33, 45, 55, 31, 43,
       44, 25, 53, 55, 40, 47, 44, 36, 22, 35, 54, 26, 47, 42, 39, 55, 45,
       36, 38, 40, 21, 36, 53, 55, 24, 38, 44, 40, 43, 23, 33, 51, 52, 44,
       44, 33, 43, 39, 29, 38, 21, 24, 53, 21, 42, 40, 31, 31, 41, 29, 35,
       29, 28, 53, 24, 47, 32, 31, 48, 43, 50, 29, 31, 27, 22, 30])

In [21]:
import numpy as np

In [22]:
sample_array=np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [23]:
rand_array=np.random.randint(0,10,5)
rand_array

array([6, 8, 8, 7, 8])

In [24]:
sample_array.min()

2

In [25]:
sample_array.argmin()

0

In [26]:
rand_array.argmin()

0

In [27]:
rand_array.argmax()

1

In [28]:
sample_array.argmax()

17

In [29]:
sample_array.dtype

dtype('int32')

In [30]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
a=np.random.rand(2,3)
a

array([[0.77228252, 0.12935266, 0.72438105],
       [0.57285482, 0.47272662, 0.38037484]])

In [33]:
a.T

array([[0.77228252, 0.57285482],
       [0.12935266, 0.47272662],
       [0.72438105, 0.38037484]])

In [34]:
import numpy as np


In [35]:
sample_array=np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [36]:
sample_array=sample_array.reshape(2,9)
sample_array

array([[10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [37]:
sample_array=sample_array.reshape(3,4)
sample_array

ValueError: cannot reshape array of size 18 into shape (3,4)

In [38]:
sample_array[1]=100
sample_array

array([[ 10,  11,  12,  13,  14,  15,  16,  17,  18],
       [100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [39]:
sample_array=np.arange(10,100)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [40]:
sample_array[1:12]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [41]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [42]:
sample_array[:]=1001
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001])

In [43]:
#Two dimensional array

In [44]:
import numpy as np

In [45]:
sample_matrix=np.array(([24,13,2,15],[15,2,54,65],[56,76,24,7]))
sample_matrix

array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [46]:
sample_matrix[2][2]

24

In [47]:
sample_matrix[1][2]

54

In [48]:
sample_matrix[:,2]

array([ 2, 54, 24])

In [49]:
sample_matrix[1,1]

2

In [50]:
sample_matrix[1:3,2:4]

array([[54, 65],
       [24,  7]])

In [51]:
sample_matrix[1:,2:]

array([[54, 65],
       [24,  7]])

In [52]:
sample_matrix[2]

array([56, 76, 24,  7])

In [53]:
import numpy as np

In [54]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [55]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [56]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [57]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [58]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])